name: "Branch build"

on: [ push ]

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - name: Check formatting
        run: nix fmt -- --fail-on-change
  
  checks:
    name: Run Nix checks
    needs: format
    strategy:
      matrix:
        # TODO: add aarch64-darwin option when available.
        os: [ "ubuntu-22.04" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - name: Run Nix checks
        run: nix flake check