name: "Deploy"

on:
  workflow_run:
    workflows: Branch build
    branches: master
    types: completed

jobs:
  build:
    name: Build configuration and push it to Cachix
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: hjdskes
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build configuration and push it to Cachix
        run: cachix watch-exec hjdskes -- nix flake check -j auto --accept-flake-config